[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = false
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".tmux/plugin/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".local/share/nvim/site/pack/lazy/start/lazy.nvim"]
  type = "git-repo"
  url = "https://github.com/folke/lazy.nvim.git"
  ref = "stable"
  clone.args = ["--depth", "1", "--branch", "stable"]
  refreshPeriod = 0
[".local/share/alacritty/themes/rose-pine"]
  type = "archive"
  url = "https://github.com/rose-pine/alacritty/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".cargo/bin/cargo-binstall-raw"]
  type = "archive"
  url = "https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-universal-apple-darwin.zip"
  refreshPeriod = 0
