---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-added-large-files
          - id: pretty-format-json
            exclude: ^\.obsidian/
            args: [--autofix]

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: shellcheck
          - id: shfmt

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.33.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.18.1
      hooks:
          - id: gitleaks

    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.13.0
      hooks:
          - id: commitizen
            stages: [commit-msg]

    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
      rev: 2.7.3
      hooks:
          - id: editorconfig-checker
            exclude: ^\.obsidian/
            alias: ec

    - repo: https://github.com/JohnnyMorganz/StyLua
      rev: v0.20.0
      hooks:
          - id: stylua
ci:
    # They don't run int pre-commit.ci, but once I move to GitHub Actions
    # https://github.com/RiddleMan/dotfiles/issues/12
    skip: [shellcheck, shfmt]
